### ISSUE TITLE
Weekly Scrum - March 14th

### ISSUE THREAD

**Issue by noahmank** [aubins11/SYSC-4806-Product-Review#20]

**Comment by noahmank** [comment]
What have I done this week? (link github issues)

What will I do next week?

What is holding me back (if applicable)?

**Comment by liyaabebe** [comment]
1- setup project, helped with login and registration, implemented user model
2- implement user degree of separation algorithm
3- n/a

**Comment by noahmank** [comment]
What have I done this week? (link github issues)
I have:
Implemented the html, class, controller, and repository for products (issue #5) 
Added one to many (and reverse) association between products and reviews

What will I do next week?
I will attempt to implement a method to calculate the Jaccard distance between two users (issue #28)

What is holding me back (if applicable)?
N/A

**Comment by adelatullio** [comment]
What have I done this week? 
Finished the Review section (html, repository, model, controller). This was github issue: https://github.com/aubins11/SYSC-4806-Product-Review/issues/4

What will I do next week?
This upcoming week I will be working on the user profile page. This is github issue: https://github.com/aubins11/SYSC-4806-Product-Review/issues/25

What is holding me back?
N/A

**Comment by aubins11** [comment]
What have I done this week? (link github issues)
I have Setup and implemented the login page and registration page

What will I do next week?
I will be linking reviews to users by mapping

What is holding me back (if applicable)?
N/A
