### ISSUE TITLE
Implement list of users whose ratings are the most "similar" to their own using the Jaccard distance.

### ISSUE THREAD

**Issue by aubins11** [aubins11/SYSC-4806-Product-Review#21]

**Comment by noahmank** [comment]
Notes for this:
- I'm not sure if you want to add a column for jaccard distances (we already have degrees of separation) to the table, or make the layout of the table change when a button is pressed to sort (first is probably easier)
- You can achieve the sorting by getting the list of users through the repository, calling currUser.sortByJaccardDistance() with those users as the arg. This will return a sorted array list of objects which contain the user and the jaccard distance, which you can add to the table however way you wish. I'm just not 100% sure how to maintain the degrees of separation info as well.
