### ISSUE TITLE
Weekly Scrum - March 21st

### ISSUE THREAD

**Issue by noahmank** [aubins11/SYSC-4806-Product-Review#37]
What have I done this week? (link github issues)

What will I do next week?

What is holding me back (if applicable)?

**Comment by noahmank** [comment]
What have I done this week? (link github issues)
- Implemented Jaccard Distance methods (and corresponding tests), issue #28 

What will I do next week?
- Implement review ranking based on jaccard distance of authors
- Add category attribute to product model

What is holding me back (if applicable)?
N/A

**Comment by adelatullio** [comment]
What have I done this week? 
I created the user profile page with the list of followers, following and past written reviews (all with test stubs). This is the linked github issue: #25 

What will I do next week?
This week I will be working on the list of most followed users to add to the user profile page (github issue #25 ) as well as getting rid of the test stubs once the user-review mapping is complete. I will also be working on the list of users with reviews most common to theirs as part of the user profile page, this is github issue #21 

What is holding me back?
The amount of school work due this week is a main thing holding me back.

**Comment by liyaabebe** [comment]
1. Implemented degree of separation of users and created a table view of all users with a "follow" button (issue #22 )
2. continue implementing degree of separation and table view of all users
3. some spring configuration knowledge regarding passing variables around views

**Comment by aubins11** [comment]
What have I done this week? (link github issues)
- Linked users to reviews by ensuring that each review created by a logged in user is associated with that user #23

What will I do next week?
- #36 
- #31 
- Debugging and cleaning up
- Updating UML diagrams

What is holding me back?
Multiple assignments and presentations due this week
