### ISSUE TITLE
Weekly Scrum - March 28th 

### ISSUE THREAD

**Issue by adelatullio** [aubins11/SYSC-4806-Product-Review#48]
What have I done this week? (link github issues)

What will I do next week?

What is holding me back (if applicable)?

**Comment by adelatullio** [comment]
What have I done this week?
Last week I finished creating the User Profile Page. This was github issue #25 

What will I do next week?
This week I will be working on implementing list of users whose ratings are the most "similar" to their own using the jaccard distance. This is github issue #21 

What is holding me back?
Last week there was a bug within the user profile page most followed users I did not catch. That took longer than I expected to find and fix, so I did not get to starting the implementation of issue #21

**Comment by noahmank** [comment]
What have I done this week? (link github issues)
Worked on adding category to the  product model (issue #24)

What will I do next week?
Working on implementing jaccard distance sorting (issue #26)

What is holding me back (if applicable)?
N/A

**Comment by liyaabebe** [comment]
What have I done this week? (link github issues)
Implemented user degree of separation #22 

What will I do next week?
Sorting of reviews #46
 
What is holding me back (if applicable)?
N/A

**Comment by aubins11** [comment]
What have I done this week? (link github issues)
Linked product reviews to users; Generated tests for verify that mapping implemented sucessfully#31 #36 #23 #35

What will I do next week?
I'll working on modifying the over style and view of the application

What is holding me back (if applicable)?
Other deliverables and assignments
