### ISSUE TITLE
Weekly Scrum - April 4th

### ISSUE THREAD

**Issue by noahmank** [aubins11/SYSC-4806-Product-Review#54]

**Comment by noahmank** [comment]
What have I done this week? (link github issues)

What will I do next week?

What is holding me back (if applicable)?

**Comment by noahmank** [comment]
What have I done this week?
Worked on issue #26 (implemented but not tested)

What will I do next week?
Finish testing for the same issue

What is holding me back (if applicable)?
covid

**Comment by liyaabebe** [comment]
1. implemented sorting of products #51 
2. finalizing tasks and project deliverables
3. n/a

**Comment by aubins11** [comment]
What have I done this week? (link github issues)
Styling and re-structuring application components #53 

What will I do next week?
Housekeeping and ensuring that everything works as it should

What is holding me back (if applicable)?
Final quizzes and assignments due this week

**Comment by adelatullio** [comment]
What have I done this week? 
This week I worked on issue #21.  

What will I do next week?
I will be cleaning up code where possible and ensuring that it works properly

What is holding me back ?
Tested positive for covid
