### ISSUE TITLE
Weekly Scrum - March 7th 

### ISSUE THREAD

**Issue by adelatullio** [aubins11/SYSC-4806-Product-Review#7]
What have I done this week? (link github issues)

What will I do next week?

What is holding me back (if applicable)?

**Comment by adelatullio** [comment]
What have I done this week?
    This week was thinking of the design of the project, setting up issues and the overall project to begin development.
What will I do next week?
    I will be working on the reviews. This includes the html template, the model class, controller as well as the repository. The link to this issue is: https://github.com/aubins11/SYSC-4806-Product-Review/issues/4
What is holding me back?
    N/A

**Comment by noahmank** [comment]
What have I done this week?
The past week has been spent considering design decisions with the team and determining our initial focus.

What will I do next week?
I will be working on the products, and everything needed to view (html template) and persist them (model, controller, repository). This is referenced by #5 

What is holding me back?
The number of projects due this week

**Comment by liyaabebe** [comment]
What have I done this week?
design decisions with the team and figuring out where/how to begin

What will I do next week?
I will be working on the users( model, controller and view) This is referenced by https://github.com/aubins11/SYSC-4806-Product-Review/issues/6

What is holding me back?
limited knowledge about spring and other projects due this week

**Comment by aubins11** [comment]
What have i done this week?
This week was spent designing and planning on our product architecture and tools

What will I do next week?
I will be working on the login page, verifying the user credentials and sending them to the product  #3.

What is holding me back?
This week is filled with quizzes, other assignments and project deadlines
